# BARE MIRROR THE REPO
#
# $git clone --bare https://github.com/mmjee/Piped-Material
# $cd Piped-Material.git
# $git push --mirror https://github.com/phixion/piped-material-docker
# $cd ..
# $rm -rf Piped-Material.git

# REGISTER REMOTE REPO WITH MY MIRROR
#
# $git clone https://github.com/phixion/piped-material-docker
# $cd piped-material-docker
# $git remote add orig https://github.com/mmjee/Piped-Material

# SYNCING THE REPOS TO TRIGGER CI
#
# $git pull orig master
# $git push origin master

name: Docker Image CI

on:
  push:
    branches:
      - 'master'
#      - 'feature-eds'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/piped-material-docker
          tags: |
            # set latest tag for master branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
#            type=raw,value=latest-eds,enable=${{ github.ref == format('refs/heads/{0}', 'feature-eds') }}
          labels: |
            maintainer=phixion
            org.opencontainers.image.title='piped-material-docker'
            org.opencontainers.image.description='dockerized version of https://github.com/mmjee/Piped-Material'
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/piped-material-docker:${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.lables }}
