# BARE MIRROR THE REPO
#
# $git clone --bare https://github.com/mmjee/Piped-Material
# $cd Piped-Material.git
# $git push --mirror https://github.com/phixion/piped-material-docker
# $cd ..
# $rm -rf Piped-Material.git

# REGISTER REMOTE REPO WITH MY MIRROR
#
# $git clone https://github.com/phixion/piped-material-docker
# $cd piped-material-docker
# $git remote add orig https://github.com/mmjee/Piped-Material

# SYNCING THE REPOS TO TRIGGER CI
#
# $git pull orig master
# $git push origin master

name: mirror remote repository
on:
  schedule:
    - cron: "0 */4 * * *"
jobs:
  mirror:
    name: mirror
    runs-on: ubuntu-latest
    steps:
      - name: git pull+push to update from remote repo
        run: |-
          git pull orig master
          git push origin master
